language: nix
sudo: true
cache:
  directories:
  - $HOME/nix.store
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
- nix copy --to file://$HOME/nix.store -f thesis/default.nix buildInputs
script:
- |
  nix-build thesis \
    --arg date "$(date +\"%Y-%m-%d\")" \
    --argstr commit "$(curl https://api.github.com/repos/chisui/dakka/git/refs/heads/master)" \
    --argstr sha256 "$(nix-prefetch-url --unpack https://github.com/chisui/dakka/archive/master.tar.gz)"
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    git clone --depth 1 -b gh-pages https://github.com/chisui/dakka web
    cd web
    cp -f $TRAVIS_BUILD_DIR/result thesis.pdf
    git add ./thesis.pdf
    git -c user.name='travis' -c user.email='travis' commit -m "travis autoupdate"
    git push -q https://chisui:$GITHUB_API_KEY@github.com/chisui/dakka &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
- nix-build
